### ISSUE TITLE
Empty list of choices checkboxGroupInput

### ISSUE THREAD

**Issue by harasmussen** [rstudio/shiny#1649]
I see that the latest release of shiny (V 1.0.1) change the way you are allowed to define a group of checkboxes. This change clashes with my use case of checkboxes and I just wanna check that my case has been considered at design.

I use checkboxes as a user controlled list where the user can add items (done with updateCheckboxGroupInput) and remove them again by checking and push a remove button. Think of the way you delete files in rstudio. This use case require me to initialize an empty checklist but the new release prevent me from doing that by throwing an error: "Please specify a non-empty vector for `choices`"

I find my example a valid case where you have to be able to initialize a checkbox group with choice = c(). What do you think? Has this use case been considered? 

Henrik

**Comment by bborgesr** [comment]
Do you have a minimal repro?

**Comment by wch** [comment]
It was an unintentional change in 1.0.1 that `choices=NULL` no longer works. (`c()` evaluates to `NULL`.) As @bborgesr mentioned, for now you can use `character(0)`.

**Comment by harasmussen** [comment]
@bborgesr Thanks for the workaround with `character(0)`. It solved my immediate problem.
@wch At least it seems inconsistent that the default argument produce an error :)

Thank you for your help. I appreciate it!

**Comment by bborgesr** [comment]
@harasmussen: given that this broke backward compatibility, we also fixed this problem in the development version of Shiny just now. So if you don't want to change your code, just install Shiny from github:

```r
devtools::install_github("rstudio/shiny")
```

As for the fact that it seems inconsistent that the default argument produces an error, I agree with you that that was less than ideal. It used to be that `choices` didn't have a default value - it used to be a required argument. In order to allow HTML for the labels of checkboxes though, it can no longer be required. Ideally, we would just get rid of `choices` and require `choiceNames` and `choiceValues`. But that of course, would break ALL apps that use checkboxGroupInput! So we need to give default values to all three of those arguments... As this whole issue pointed out, it's hard to build new features of top of software that wasn't designed with these in mind. Hopefully, we now achieved that for this one case, at least. 

Thanks for the report!

**Comment by harasmussen** [comment]
@bborgesr Nice! I was looking for the name/value separation :).

**Comment by worker-wang2019** [comment]
I still dont get it , where should I made change wrt choice ?

I still get the same 
error Error in normalizeChoicesArgs(choices, choiceNames, choiceValues) : 
  Please specify a non-empty vector for `choices` (or, alternatively, for both `choiceNames` AND `choiceValues`).

#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Old Faithful Geyser Data"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         sliderInput("bins",
                     "Number of bins:",
                     min = 1,
                     max = 50,
                     value = 30)
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("distPlot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
   output$distPlot <- renderPlot({
      # generate bins based on input$bins from ui.R
      x    <- faithful[, 2] 
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      
      # draw the histogram with the specified number of bins
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
   })
}

# Run the application 
shinyApp(ui = ui, server = server)

**Comment by worker-wang2019** [comment]
Sorry to bring this back up again . I am still getting this error in year of 2019 

Loading required package: shiny
Error in normalizeChoicesArgs(choices, choiceNames, choiceValues) : 
  Please specify a non-empty vector for `choices` (or, alternatively, for both `choiceNames` AND `choiceValues`).

and it all begins with running the sample app from Rstudio .
IT says it need update version of shiny , but when I tried to instll from github , it says

 package ‘fastmap’ is not available (for R version 3.5.1)
any one can help ?



library(shiny)


ui <- fluidPage(
   

   titlePanel("Old Faithful Geyser Data"),
   

   sidebarLayout(
      sidebarPanel(
         sliderInput("bins",
                     "Number of bins:",
                     min = 1,
                     max = 50,
                     value = 30)
      ),
      

      mainPanel(
         plotOutput("distPlot")
      )
   )
)


server <- function(input, output) {
   
   output$distPlot <- renderPlot({

      x    <- faithful[, 2] 
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      

      hist(x, breaks = bins, col = 'darkgray', border = 'white')
   })
}

 
shinyApp(ui = ui, server = server)
