### ISSUE TITLE
Bug: empty bookmarks on Windows are not "read" correctly

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1689]
In the following app, click "Bookmark" and then follow the new URL:

```r
library(shiny)
ui <- function(request) {
  fluidPage(
    textInput("txt", "Enter text"),
    bookmarkButton()
  )
}
server <- function(input, output, session) {}
shinyApp(ui, server, enableBookmarking = "url")
```

On Macs, this works fine. On Windows, it will always show a notification saying:
> Error in RestoreContext initialization: Failed to parse URL parameter "txt"

Originally from here: http://stackoverflow.com/questions/43685561/r-shiny-bookmark-button-flaw

**Comment by wch** [comment]
It's because of this issue which I've filed in the jsonlite repo: jeroen/jsonlite#180. But the root cause is a bug in R, where `file.exists('""')` always TRUE.

**Comment by tsouchlarakis** [comment]
Any idea when/if this will be addressed?

**Comment by jeroen** [comment]
@tsouchlarakis @bborgesr Installing the development version of jsonlite should fix it?

```r
source("https://install-github.me/jeroen/jsonlite")
```

**Comment by wch** [comment]
Closing here because it's a jsonlite issue, and it's fixed now.

**Comment by tsouchlarakis** [comment]
Only when I run that line of code to install the development version of jsonlite, I get this error:

```
> source("https://install-github.me/jeroen/jsonlite")
Downloading GitHub repo jeroen/jsonlite@master
Installing package into ‘C:/Users/anthonys/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
* installing *source* package 'jsonlite' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB="jsonlite.dll" OBJECTS="base64.o collapse_array.o collapse_object.o collapse_pretty.o escape_chars.o integer64_to_na.o is_datelist.o is_recordlist.o is_scalarlist.o modp_numtoa.o null_to_na.o num_to_char.o parse.o prettify.o push_parser.o r-base64.o register.o row_collapse.o transpose_list.o validate.o"' had status 127
ERROR: compilation failed for package 'jsonlite'
* removing 'C:/Users/USER/Documents/R/win-library/3.3/jsonlite'
* restoring previous 'C:/Users/USER/Documents/R/win-library/3.3/jsonlite'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\USER\Documents\R\win-library\3.3\00LOCK-jeroen-jsonlite-e181501\jsonlite\libs\x64\jsonlite.dll to C:\Users\USER\Documents\R\win-library\3.3\jsonlite\libs\x64\jsonlite.dll: Permission denied
```

And if I restart RStudio and retry:
```
> source("https://install-github.me/jeroen/jsonlite")
Downloading GitHub repo jeroen/jsonlite@master
Installing package into ‘C:/Users/USER/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
* installing *source* package 'jsonlite' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB="jsonlite.dll" OBJECTS="base64.o collapse_array.o collapse_object.o collapse_pretty.o escape_chars.o integer64_to_na.o is_datelist.o is_recordlist.o is_scalarlist.o modp_numtoa.o null_to_na.o num_to_char.o parse.o prettify.o push_parser.o r-base64.o register.o row_collapse.o transpose_list.o validate.o"' had status 127
ERROR: compilation failed for package 'jsonlite'
* removing 'C:/Users/USER/Documents/R/win-library/3.3/jsonlite'
* restoring previous 'C:/Users/USER/Documents/R/win-library/3.3/jsonlite'
Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package jsonlite has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools and make sure it is in the PATH.
2: running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\USER\Documents\R\win-library\3.3" "C:/Users/USER/AppData/Local/Temp/RtmpuKT6Vh/remotes260072eb501e/jeroen-jsonlite-e181501"' had status 1 
3: In utils::install.packages(...) :
  installation of package ‘C:/Users/USER/AppData/Local/Temp/RtmpuKT6Vh/remotes260072eb501e/jeroen-jsonlite-e181501’ had non-zero exit status
```

And the bookmarking problem persists. Any ideas?

**Comment by wch** [comment]
Since jsonlite has compiled code, you need Rtools, which you can download here: https://cran.r-project.org/bin/windows/Rtools/

**Comment by tsouchlarakis** [comment]
Downloaded Rtools. `find_rtools()` returns `TRUE`, but when I run the source command for the jsonlite package the same error appears. It should be added that I do not have admin rights for the computer I am working on. Could this be affecting the Rtools installation?

**Comment by wch** [comment]
If it's the first error, you need to restart R to have a clean session before installing the package. (On Windows, you can't install over a package that's currently loaded.)

**Comment by tsouchlarakis** [comment]
It's the second error, the one that ends with `non-zero exit status`.

**Comment by wch** [comment]
It sounds like it's still having trouble finding Rtools. This might help: https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows

**Comment by tsouchlarakis** [comment]
Shoot. I'm not admin, so it won't let me edit the PATH because access is denied. Would `find_rtools()` return `TRUE` if it couldn't find Rtools though? It does return `TRUE` for me.

**Comment by wch** [comment]
You may need to edit your user's PATH variable.

This might be helpful. You can ignore the part about miktex and just pay attention to the Rtools part: 
https://gist.github.com/ofurkusi/09a432ed1fb15c72eec9#add-r-tools-and-miktex-to-path

Also:
http://stackoverflow.com/questions/41573450/how-to-install-rtools-without-admin-privileges-on-windows

**Comment by tsouchlarakis** [comment]
I see. I'll try installing downloading RTools on a PC where I have admin rights, then copy over via USB stick. Hopefully, however, this issue will be resolved soon for Windows users.
