### ISSUE TITLE
Updating input data extremely frequently may lead to a message box from DataTables

### ISSUE THREAD

**Issue by yihui** [rstudio/shiny#561]
see

- https://groups.google.com/forum/#!topic/shiny-discuss/xqcYhR7SXPU
- https://gallery.shinyapps.io/012-datatables/
- http://datatables.net/manual/tech-notes/4

**Comment by sharko666** [comment]
I have found this dataTables page were they explain how to turn the warnings in datatables off.

http://www.datatables.net/forums/discussion/3059/is-there-any-way-to-disable-the-warnings-issued-by-datatable

This would solve that problem for me because the warning pops up even though the table is presented correctly.

Unfortunatly I have no idea how to do that in shiny. Is that somehow possible?

**Comment by yihui** [comment]
@sharko666 I'm not sure if that would be an ideal solution, but you can certainly cure the symptom at least. You can insert this to your UI:

```r
tags$head(tags$script("$(function() {$.fn.dataTableExt.errMode = 'throw';});"))
```

**Comment by sharko666** [comment]
It is certainly not an ideal solution, but I also tried the DT development package and the problem remains. The only other solution I see would be to define my own output widget using bootstrap tables instead of datatables. Not sure whether this would solve it though.

**Comment by sharko666** [comment]
This does not work for me. The javascript error is 
TypeError: $.fn.dataTableExt is undefined
Do I have to import this .dataTableExt somehow?

**Comment by sharko666** [comment]
The code below worked for me. Its a slightly better solution. I stole it from 

http://stackoverflow.com/questions/11941876/correctly-suppressing-warnings-in-datatables

<code>
window.alert = (function() {
    var nativeAlert = window.alert;
    return function(message) {
        //window.alert = nativeAlert;
        message.indexOf("DataTables warning") === 0 ?
            console.warn(message) :
            nativeAlert(message);
    }
</code>
})();

Note, I commented out the line which restores the original behaviour after first occurrence as suggested by the author in the stackoverflow thread.

**Comment by yihui** [comment]
Could you post a minimal reproducible example that uses DT and shows the error message? I have been requesting such an example, but nobody has provided one so far. It is really difficult to solve a problem that I'm unable to reproduce. Thanks!

**Comment by sharko666** [comment]
My application is already quite complicated but I can try?

**Comment by yihui** [comment]
I'll appreciate it. If you really cannot reduce the example any more, you can just send me the "complicated" version and I'll see if I can figure out the problem.

**Comment by yihui** [comment]
With the current development version of shiny, you can insert `tags$script("$(function() {$.fn.dataTableExt.errMode = 'none';});")` anywhere (if possible) in ui.R to suppress the warning. Please test it by `devtools::install_github('rstudio/shiny')`.

**Comment by jcheng5** [comment]
Do we know that it's always safe to ignore the warning (and thus should enable it by default)? Or is this something users should be forced to opt into, and if so, how much do we encourage/discourage it?

**Comment by yihui** [comment]
@jcheng5 It does look like a wrong solution (fixing the problem by hiding it), and I'm not sure how many more hours I should spend on it. A slightly better solution is

```js
tags$script("$(function() {
  $.fn.dataTableExt.errMode = function(settings, tn, msg) { console.log(msg); };
});")
```

But again it does not really solve the problem. I guess it is not harmful, and I do not encourage or discourage it. My current guess is that the tables they tried to render are pretty big, and if they change the data extremely frequently (e.g. check/uncheck the columns at https://gallery.shinyapps.io/012-datatables/), R may be slow to respond, then for some reason, the Ajax call may return a data object of 8 columns whereas the current table on the page still has 9 columns. DataTables will warn in this case with an alert box. I do not think it is harmful to hide the warning in this particular case, since the user will see an empty table temporarily. After R finishes responding to the last change on the page, the table should be displayed correctly. Here is my own reproducible example (I have not received any examples from users yet so I do not know if they had the same problem):

```r
library(shiny)
shinyApp(
  ui = fluidPage(actionButton('x1', 'Change'), dataTableOutput('x2')),
  server = function(input, output) {
    output$x2 = renderDataTable({
      input$x1
      n = rpois(1, 6)
      as.data.frame(matrix(rnorm(n * 1e6), ncol = n))
    })
  }
)
```

I'd love to know what you think.

**Comment by sharko666** [comment]
I was not be able to recover the error with the DT package. If I use the DT package the application freezes for a while until the data is loaded. No error is thrown. It is slightly slower but as far as I can tell stable in terms of this issue. I must have made a mistake in my previous post.

**Comment by zross** [comment]
For the record, I'm having this issue as well. When I delete fields quickly I'm getting that same warning. This link will not exist for too long but [https://spatial.shinyapps.io/WHO_HETK](https://spatial.shinyapps.io/WHO_HETK) has an example where if you delete the fields on the default table quickly the warning pops up.

```r
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinythemes_1.0.1  dplyr_0.4.3        RColorBrewer_1.1-2 ggplot2_1.0.1     
[5] shinyBS_0.62       shiny_0.12.2      

loaded via a namespace (and not attached):
 [1] assertthat_0.1   colorspace_1.2-6 DBI_0.3.1        digest_0.6.8    
 [5] gtable_0.1.2     htmltools_0.2.6  httpuv_1.3.3     jsonlite_0.9.17 
 [9] labeling_0.3     lazyeval_0.1.10  magrittr_1.5     MASS_7.3-44     
[13] mime_0.4         munsell_0.4.2    parallel_3.1.2   plyr_1.8.3      
[17] proto_0.3-10     R6_2.1.1         Rcpp_0.12.1      reshape2_1.4.1  
[21] rstudioapi_0.2   scales_0.3.0     stringi_1.0-1    stringr_1.0.0   
[25] tools_3.1.2      xtable_1.8-0  
```

**Comment by wch** [comment]
Oh hm, it looks like it's using the GitHub version of htmltools, in which which `htmlTemplate` has a new `text_` argument. You could change the Travis config to get htmltools from CRAN.

**Comment by yihui** [comment]
This bug should be fixed in the current development version of shiny now. Please `devtools::install_github('rstudio/shiny')` if you want to test it. Thanks!

**Comment by kevinrue** [comment]
> This bug should be fixed in the current development version of shiny now. Please devtools::install_github('rstudio/shiny') if you want to test it. Thanks!

Hi Yihui,
Thanks a lot for having looked into the issue.
However, I just did the above (it installed shiny version 0.13.2.9003) and I still get the pop ups. My app is not particularly complex, the datatable is "only" 300 rows by pages of 10, but it is sensitive data therefore I cannot immediately provide you a small reproducible example.

I have also just tested your reproducible example above:

> library(shiny)
shinyApp(
  ui = fluidPage(actionButton('x1', 'Change'), dataTableOutput('x2')),
  server = function(input, output) {
    output$x2 = renderDataTable({
      input$x1
      n = rpois(1, 6)
      as.data.frame(matrix(rnorm(n * 1e6), ncol = n))
    })
  }
)

which also triggers the popup if I click the button a few times quickly.

Similarly, I also tried the two tags$ based methods in ui.R, and still have the same problem:
> tags$script("$(function() {
  $.fn.dataTableExt.errMode = function(settings, tn, msg) { console.log(msg); };
});")

> tags$script("$(function() {$.fn.dataTableExt.errMode = 'none';});"),

**Comment by yihui** [comment]
@kevinrue Could you try the DT package instead? https://github.com/rstudio/DT http://rstudio.github.io/DT/shiny.html

**Comment by kevinrue** [comment]
I was indeed using the package DT (version 0.1, with "install.packages"), but installing the devel (using "devtools") fixed the issue. Thanks a lot !
For future reference (and users browsing this issue): when should we expect the next release of the DT package available using install.packages?

**Comment by jdonnell01** [comment]
Hello,

Is there an accepted solution to disabled these DT javascript alerts? My R Shiny application is throwing spurious Javascript alerts related to the DT library: https://datatables.net/manual/tech-notes/7.

I need to disable these alerts as they are not genuine and are extremely disruptive to users. I attempted to disable the alerts with this below code snippet, however I see there is an error in the browser console:

      tags$head(tags$script('$(document).ready(function() {
                     $.fn.dataTable.ext.errMode = "none";
                     })')),
ERROR:
Uncaught TypeError: Cannot set property 'ext' of undefined

Is it possible to disable these Javascript alerts?
