### ISSUE TITLE
block to IE7 standard in a IE9 browser

### ISSUE THREAD

**Issue by bthieurmel** [rstudio/shiny#695]
Hi, 
Due to our system (I think...), all shiny apps are open in a IE9 browers with a document standard to IE7. So some functionnalities are not available, and the apps bugs a lot...

The only we found to resolve the problem is to change the write preamble of the renderPage() function

``` coffee
'<!DOCTYPE html>',
 '<html>,'

to 

'<!DOCTYPE html>',
               '<meta http-equiv="X-UA-Compatible" content="IE=Edge">',
               '<html>',
```

All others type of inclusion of the line `<meta http-equiv="X-UA-Compatible" content="IE=Edge">` fail.

So is-there a better solution to fix this, without modifying source package ?

Thanks

**Comment by bthieurmel** [comment]
Perhaps, the question can be : is-there a way to insert a meta balise before the first shiny meta ?
````
'<head>',
               '  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'
```

**Comment by wch** [comment]
Adding that header sounds like a reasonable fix to me. @jcheng5 do you know of any reason that might be a problem?

**Comment by jcheng5** [comment]
I'd rather have it be an actual http header, any objection to that?

**Comment by wch** [comment]
That sounds good to me.

**Comment by jcheng5** [comment]
Fixed in f54a6e85136b321822dab033e60711485d3fe36b. @bthieurmel, can you try installing the latest?

```r
devtools::install_github("rstudio/shiny")
```

and then restart your R session.

**Comment by bthieurmel** [comment]
Thanks. We'll test the fixed version tomorrow on the environment presenting this problem, and we come back to you!

**Comment by bthieurmel** [comment]
After some tests, it's seems that some problems are solve, but some graphics bugs persist....
We'll look for more tests next week.

**Comment by wch** [comment]
@bthieurmel Is this still an issue? Recent released versions of Shiny incorporate this fix.
