### ISSUE TITLE
updateSelectize can't alphabetize on the server side! - choices are re-ordered

### ISSUE THREAD

**Issue by johnpauls** [rstudio/shiny#865]
I have run into an odd bug using shiny 0.12.1. If you use updateSelectizeInput, and use the server=TRUE option, then the choices are slightly reordered. 

Here is a simple app that uses updateSelectize and has for its choices `letters[1:20]`. When the whole thing is on the client side, or when it is updated on the server side with `server=FALSE` it behaves as expected. When `server=TRUE` however, the choices are out of order. Rather than `a, b, c,...` for the first 3 choices,  you get `k, a, c,...`, and the `b` is down where the `k`  should be.

```r
library(shiny)

shinyApp(ui = fluidPage(
  
  selectizeInput(inputId="Input1", label="Client-side Selectize", choices=letters[1:20]),
  
  selectizeInput(inputId="Input2", label="Server-side Selectize, server=FALSE", choices=NULL),
  
  selectizeInput(inputId="Input3", label="Server-side Selectize, server=TRUE", choices=NULL) 
  
),
server = function(input,output,session){
  
 updateSelectizeInput(session, inputId="Input2", label="Server-side Selectize", choices =letters[1:20],server=FALSE) 
  
 updateSelectizeInput(session, inputId="Input3", label="Server-side Selectize", choices =letters[1:20],server=TRUE)   
  
})
```

**Comment by yihui** [comment]
Thanks for the report. I can reproduce it in Chrome. That is weird. It works in the RStudio preview window, though.

**Comment by johnpauls** [comment]
Oh, I should have mentioned that I was using Opera when I saw it.

**Comment by yihui** [comment]
This should be fixed by #939. Could you test `devtools::install_github('yihui/shiny@bugfix/selectize-selected')`? Thanks!

**Comment by johnpauls** [comment]
It seems to be working correctly. Thanks

**Comment by blacksheep07** [comment]
Hi @yihui. I still see this issue using `0.12.2`, but using `as.numeric`. The order seems to be `11, 1, 3, ... 10, 2, 12...` with any `as.numeric` option.

Using @johnpauls's modified example:

library(shiny)

shinyApp(ui = fluidPage(
				
				selectizeInput(inputId="Input1", label="Client-side Selectize", choices=(1:20)),
				
				selectizeInput(inputId="Input2", label="Server-side Selectize, server=FALSE", choices=NULL),
				
				selectizeInput(inputId="Input3", label="Server-side Selectize, server=TRUE", choices=NULL) 
		
		),
		server = function(input,output,session){
			
			updateSelectizeInput(session, inputId="Input2", label="Server-side Selectize", choices = (1:20), server=FALSE) 
			
			updateSelectizeInput(session, inputId="Input3", label="Server-side Selectize", choices = (1:20), server=TRUE)   
			
		})

**Comment by yihui** [comment]
@blacksheep07 I cannot reproduce the problem using the example you provided above. The order is 1, 2, ..., 20 in my browser.

**Comment by blacksheep07** [comment]
![screen shot 2015-12-10 at 3 09 44 pm](https://cloud.githubusercontent.com/assets/16240771/11724016/2aa1be58-9f50-11e5-8874-681f05c818f9.png)

I am using R 3.2.2_1 x64 with Java SE 8 1.8.0_66 on a MacBook Air running OS X El Capitan 10.11.2. I am executing the app from inside Eclipse

**Comment by yihui** [comment]
This issue was fixed after shiny 0.12.2 was released to CRAN, so please test the current development version: `devtools::install_github('rstudio/shiny')`

**Comment by blacksheep07** [comment]
Thank you. This update fixed the problem.
