### ISSUE TITLE
unicode inequalities (u2264 and u2265) not working on windows

### ISSUE THREAD

**Issue by garthtarr** [rstudio/shiny#961]
**The issue is that the options in selectInput lists with unicode characters appear to be ignored.**

This bug is specifically related to Windows (I've tested with Windows 7 and Windows 10).  The MWE below works perfectly on unix-type systems (tested on OS X 10.10.5 and Ubuntu 14.04).

The issue is related to certain unicode characters, specifically u2264 and u2265, though there probably are others.

It's not obvious if this is an R issue or a shiny issue, [though in discussion](https://groups.google.com/forum/#!topic/shiny-discuss/3KDGxupzRRQ) with @yihui, he suggested I open an issue here.  I have tested on the latest R-devel build for Windows and the issue is still present:

```
> sessionInfo()
R Under development (unstable) (2015-09-20 r69402)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.2.9003

loaded via a namespace (and not attached):
 [1] R6_2.1.1         htmltools_0.2.9  tools_3.3.0      rstudioapi_0.3.1
 [5] Rcpp_0.12.1      jsonlite_0.9.17  digest_0.6.8     xtable_1.7-4    
 [9] httpuv_1.3.3     mime_0.4
```

A work around (as suggested by @yihui) is to change the locale from English (the default on my machine) to Chinese:

```
if (.Platform$OS.type != "unix") Sys.setlocale("LC_CTYPE", "Chinese")
```

Another work around is to not use windows machines - unfortunately that's not always possible.

Here's the MWE:

```
require(shiny)
app <- shinyApp(
  ui = fluidPage(
    "\u2264 and \u2265",
    uiOutput("bin_prob_k"),
    uiOutput("bin_prob_inequality"),
    uiOutput("bin_prob_out"),
    plotOutput("pmf")
  ),
  server = function(input, output) {
    
    output$bin_prob_k = renderUI({
      numericInput("binom4_k", label = "Number of successes (k)", value = 3,
                   step = 1, min = 0, max = 10)
    })
    
    bin_choices = reactive({
      nms = paste("P(X",c("=","\u2264","<","\u2265",">"),input$binom4_k,")",sep="")
      return(nms)
    })
    
    output$bin_prob_inequality = renderUI({
      selectInput("bin_prob_type", label = "Inequality type", choices = bin_choices())
    })
    
    output$pmf <- renderPlot({
      n=10
      prob = 0.4
      probs = dbinom(0:n, size=n, prob=prob)
      mtext(input$bin_prob_type, side = 3, col = "red", cex = 1.2)
    })
    
    output$bin_prob_out = renderUI({
      withMathJax(paste0("\\(",input$bin_prob_type,"\\)",sep=""))
    })
  }
)
```

Looking closely, when the locale is English, the `\u2264 and \u2265` characters included as the first element in the ui render as equals signs.  This might suggest that in the background somewhere, the inequalities are being rendered as equals and then only the unique values are being displayed.

When the locale is changed to Chinese, the first element in the ui displays the inequalities correctly and the selectInput has all 5 entries displayed correctly.

**Comment by yihui** [comment]
Thanks for the detailed report. My quick guess is that removing the two `enc2native` calls in shiny should fix the problem with the current development version of R, and my blind fix can be installed by

```r
devtools::install_github('yihui/shiny@bugfix/961-unicode')
# restart R and reload the app
```

If you use the development version of R on Windows, could you try this and see if the Unicode characters are preserved? Thanks!

**Comment by garthtarr** [comment]
That build is a partial fix (with the current R-devel version).

It fixes the rendering in the selectInput dropdown list and the inequalities appear correctly in the renderUI output (`bin_prob_out`).

I also tested it with the current R release (3.2.2) where it doesn't work (but you seemed to already know that that would be the case!)

**Remaining issue:**

The first input of plain text into the ui is still rendered as equal signs.  Is there another `enc2native` call on plain text input into the UI?  It's the same when the text is passed through `textOutput`/`renderText` pair.

**Comment by yihui** [comment]
There isn't another `enc2native` call, but there might be functions that quietly convert the character encoding to native encoding. I just pushed another guess. Could you reinstall that branch and try again?

**Comment by garthtarr** [comment]
Unfortunately, that guess didn't resolve it.

Just to make sure, I uninstalled shiny then reinstalled using the above repo, restarting R every step of the way.

It's interesting that the `renderUI` works but the `renderText` doesn't (in that it converts the inequality to an equals sign).

    output$caption <- renderText({
      return("\u2264")
    })
    
    output$bin_prob_out = renderUI({
     return("\u2264")
    })

**Comment by yihui** [comment]
Okay, since I have already started, I took a deeper look into it and the original issue should be fixed in that branch now (again, you need the development versions of R and htmltools: `devtools::install_github('rstudio/htmltools')`)

Re: `renderText()`, that is sort of expected, because `renderText()` uses `capture.output()`, and the inequality sign can be lost during that. I think this is a separate bug of shiny. One workaround is to replace renderText() with a normal function ,e.g.

```r
output$caption <- function() {
  return("\u2264")
}
```

**Comment by garthtarr** [comment]
You're right, renderText() still doesn't work, but using a normal function does work as expected and including unicode characters directly in the UI also works perfectly.

Now we wait for R 3.3.x to hit the main stream!

Thanks for all your help!

**Comment by yihui** [comment]
Sadly now it fails with the Chinese locale... I love Windows.

**Comment by garthtarr** [comment]
Yep, I can confirm that!

**Comment by yihui** [comment]
Alright. Turns out to be a simple fix. Now both English and Chinese locales should work. Actually I also tested R 3.2.2 and it seems to work as well for me.

**Comment by garthtarr** [comment]
Yep, that's it!  I can confirm that your fixes work for R 3.2.2 (and R-devel) in Chinese and English locales as long as you have the most recent version of htmltools installed:

```
devtools::install_github('rstudio/htmltools')
devtools::install_github('yihui/shiny@bugfix/961-unicode')
```

I can also confirm that this does not impact unix systems - it continues to work under unit as it always has.

**Comment by yihui** [comment]
Thanks for the confirmation! We still need to wait for the next version of R for a more fundamental fix. Although R 3.2.2 works for this particular example, it does not work for another test of mine (R-devel works).

**Comment by yihui** [comment]
FYI, the fix in base R I mentioned has been incorporated into the patched version of R, but you may have to wait until tomorrow for the Windows build: https://cran.rstudio.com/bin/windows/base/rpatched.html

**Comment by yihui** [comment]
Hi, I have figured out how to make it work for R <= 3.2.2 as well. You can install that branch and test it if you want. Hopefully you don't have to wait for R 3.3.0 which is supposed to appear in spring next year.

**Comment by garthtarr** [comment]
That's fantastic - works perfectly with current R releases on my windows machine!  It's very useful to have this working with the current version of R (without having to resort to the Chinese locale trick).

**Comment by kadrach** [comment]
This issue still occurs when I use a named list with Shiny, e.g. to pass in a "display name" and the value.

```r
radioButtons("cutoff",
             label = "Cutoff",
             choices = list("\u2264 10" = "less10")),
```
renders as 
![image](https://cloud.githubusercontent.com/assets/206176/18296045/cd8d53b0-74e9-11e6-846e-9fe4447a8d35.png)

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinydashboard_0.5.1 futile.logger_1.4.3  shiny_0.13.2        

loaded via a namespace (and not attached):
 [1] R6_2.1.2             htmltools_0.3.5      tools_3.3.1          lambda.r_1.1.9       Rcpp_0.12.5          futile.options_1.0.0 jsonlite_1.0        
 [8] digest_0.6.9         xtable_1.8-2         httpuv_1.3.3         mime_0.4    
```
