### ISSUE TITLE
runApp() opens incorrect URL for RStudio servers

### ISSUE THREAD

**Issue by erichare** [rstudio/shiny#98]
Absolutely loving Shiny.  Great job.  I did notice one issue in my testing.  If I'm working off a remote RStudio server (or, theoretically, a remote R server although I've yet to do this), and I go to run an app with runApp(), a browser pops up attempting to connect to localhost:8100 rather than rstudio_server_url:8100.  The relevant code is this line:

appUrl <- paste("http://localhost:", port, sep = "")

Is there any way that the URL of the server instance (as retrieved from the browser) can be used instead of localhost, if running in an rstudio server?

**Comment by jafflerbach** [comment]
Has this been fixed? Just tried running [this gist](https://gist.github.com/jcheng5/a1c48a18d0ea3623c0e6) on RStudio Server and it runs yet nothing is showing up in the viewer pane, or in an external window when using shinyApp(ui, server,options = list(launch.browser =TRUE))

I've had this problem with other shinyapps as well...is there documentation on running shiny from rstudio server?

**Comment by yihui** [comment]
@jafflerbach What is your RStudio Server version? I believe it have been fixed. However, you need to make sure your web browser does not block pop-up windows from RStudio Server.

**Comment by jafflerbach** [comment]
RStudio Server version version is 0.98.1091

My web browser pop-up blocker is disabled, and it is still failing to load.

**Comment by yihui** [comment]
@jafflerbach Can you try a more recent version? http://www.rstudio.com/products/rstudio/download-server/ Sorry I do not work on RStudio Server, so I may not be the best person to answer this question.
